# Generated by Django 2.2.6 on 2019-10-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0002_auto_20191003_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('submitter', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('predictions', models.TextField()),
                ('published', models.DateTimeField(verbose_name='date submitted')),
            ],
        ),
    ]
